In [1]:
pip install pandas fg-data-profiling

Requirement already satisfied: pandas in /usr/local/lib/python3.13/dist-packages (2.2.3)
Collecting fg-data-profiling
  Downloading fg_data_profiling-4.19.1-py2.py3-none-any.whl.metadata (23 kB)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas) (2026.3)
Requirement already satisfied: scipy<1.17,>=1.8 in /usr/local/lib/python3.13/dist-packages (from fg-data-profiling) (1.16.3)
Requirement already satisfied: matplotlib<=3.10,>=3.5 in /usr/local/lib/python3.13/dist-packages (from fg-data-profiling) (3.10.0)
Requirement already satisfied: pydantic<3,>=2 in /usr/local/lib/python3.13/dist-packages (from fg-data-profiling) (2.13.4)
Requirement already satisfied: PyYAML<6.1,>=6.0.3 in /usr/local/lib/python3.13/dist-packages (from fg-data-profiling) (6.0.3)
Requirement already satisfied: jinja2<3.2,>=3.1.6 in /usr/local/lib/python3.13/dist-packages (from fg-data-profiling) (3.1.6)
Collecting visions<0.8.2,>=0.7.5 (from visions[type_image_path]<0.8.2,>=0.7.5->fg-data-profiling)
  Downloading visions-0.8.1-py3-none-any.whl.metadata (11 kB)
Collecting minify-html>=0.15.0 (from fg-data-profiling)
  Downloading minify_html-0.18.1-cp313-cp313-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (18 kB)
Collecting filetype>=1.0.0 (from fg-data-profiling)
  Downloading filetype-1.2.0-py2.py3-none-any.whl.metadata (6.5 kB)
Collecting phik<0.13,>=0.12.5 (from fg-data-profiling)
  Downloading phik-0.12.5-cp313-cp313-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (5.6 kB)
Requirement already satisfied: requests<3,>=2.32.0 in /usr/local/lib/python3.13/dist-packages (from fg-data-profiling) (2.32.4)
Requirement already satisfied: tqdm<5,>=4.66.3 in /usr/local/lib/python3.13/dist-packages (from fg-data-profiling) (4.67.3)
Requirement already satisfied: seaborn<0.14,>=0.10.1 in /usr/local/lib/python3.13/dist-packages (from fg-data-profiling) (0.13.2)
Collecting multimethod<2,>=1.4 (from fg-data-profiling)
  Downloading multimethod-1.12-py3-none-any.whl.metadata (9.6 kB)
Requirement already satisfied: statsmodels<1,>=0.13.2 in /usr/local/lib/python3.13/dist-packages (from fg-data-profiling) (0.14.6)
Requirement already satisfied: typeguard<5,>=4 in /usr/local/lib/python3.13/dist-packages (from fg-data-profiling) (4.6.0)
Collecting imagehash==4.3.2 (from fg-data-profiling)
  Downloading ImageHash-4.3.2-py2.py3-none-any.whl.metadata (8.4 kB)
Requirement already satisfied: wordcloud>=1.9.4 in /usr/local/lib/python3.13/dist-packages (from fg-data-profiling) (1.9.6)
Collecting dacite<2,>=1.9 (from fg-data-profiling)
  Downloading dacite-1.9.2-py3-none-any.whl.metadata (17 kB)
Requirement already satisfied: numba<0.63,>=0.60 in /usr/local/lib/python3.13/dist-packages (from fg-data-profiling) (0.61.2)
Requirement already satisfied: PyWavelets in /usr/local/lib/python3.13/dist-packages (from imagehash==4.3.2->fg-data-profiling) (1.9.0)
Requirement already satisfied: pillow in /usr/local/lib/python3.13/dist-packages (from imagehash==4.3.2->fg-data-profiling) (11.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.13/dist-packages (from jinja2<3.2,>=3.1.6->fg-data-profiling) (3.0.3)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.13/dist-packages (from matplotlib<=3.10,>=3.5->fg-data-profiling) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.13/dist-packages (from matplotlib<=3.10,>=3.5->fg-data-profiling) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.13/dist-packages (from matplotlib<=3.10,>=3.5->fg-data-profiling) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.13/dist-packages (from matplotlib<=3.10,>=3.5->fg-data-profiling) (1.5.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.13/dist-packages (from matplotlib<=3.10,>=3.5->fg-data-profiling) (26.3)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.13/dist-packages (from matplotlib<=3.10,>=3.5->fg-data-profiling) (3.3.2)
Requirement already satisfied: llvmlite<0.45,>=0.44.0dev0 in /usr/local/lib/python3.13/dist-packages (from numba<0.63,>=0.60->fg-data-profiling) (0.44.0)
Requirement already satisfied: joblib>=0.14.1 in /usr/local/lib/python3.13/dist-packages (from phik<0.13,>=0.12.5->fg-data-profiling) (1.5.3)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.13/dist-packages (from pydantic<3,>=2->fg-data-profiling) (0.8.0)
Requirement already satisfied: pydantic-core==2.46.4 in /usr/local/lib/python3.13/dist-packages (from pydantic<3,>=2->fg-data-profiling) (2.46.4)
Requirement already satisfied: typing-extensions>=4.14.1 in /usr/local/lib/python3.13/dist-packages (from pydantic<3,>=2->fg-data-profiling) (4.16.0)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.13/dist-packages (from pydantic<3,>=2->fg-data-profiling) (0.4.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.13/dist-packages (from requests<3,>=2.32.0->fg-data-profiling) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.13/dist-packages (from requests<3,>=2.32.0->fg-data-profiling) (3.18)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.13/dist-packages (from requests<3,>=2.32.0->fg-data-profiling) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.13/dist-packages (from requests<3,>=2.32.0->fg-data-profiling) (2026.7.22)
Requirement already satisfied: patsy>=0.5.6 in /usr/local/lib/python3.13/dist-packages (from statsmodels<1,>=0.13.2->fg-data-profiling) (1.0.2)
Requirement already satisfied: attrs>=19.3.0 in /usr/local/lib/python3.13/dist-packages (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->fg-data-profiling) (26.1.0)
Requirement already satisfied: networkx>=2.4 in /usr/local/lib/python3.13/dist-packages (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->fg-data-profiling) (3.6.1)
Collecting puremagic (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->fg-data-profiling)
  Downloading puremagic-2.2.0-py3-none-any.whl.metadata (7.3 kB)
Downloading fg_data_profiling-4.19.1-py2.py3-none-any.whl (400 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 400.3/400.3 kB 3.0 MB/s eta 0:00:00
Downloading ImageHash-4.3.2-py2.py3-none-any.whl (296 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 296.7/296.7 kB 17.6 MB/s eta 0:00:00
Downloading dacite-1.9.2-py3-none-any.whl (16 kB)
Downloading filetype-1.2.0-py2.py3-none-any.whl (19 kB)
Downloading minify_html-0.18.1-cp313-cp313-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.1/3.1 MB 24.8 MB/s eta 0:00:00
Downloading multimethod-1.12-py3-none-any.whl (10 kB)
Downloading phik-0.12.5-cp313-cp313-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (682 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 682.5/682.5 kB 44.3 MB/s eta 0:00:00
Downloading visions-0.8.1-py3-none-any.whl (105 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 105.4/105.4 kB 11.5 MB/s eta 0:00:00
Downloading puremagic-2.2.0-py3-none-any.whl (71 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 72.0/72.0 kB 4.3 MB/s eta 0:00:00
Installing collected packages: minify-html, filetype, puremagic, multimethod, dacite, imagehash, visions, phik, fg-data-profiling
Successfully installed dacite-1.9.2 fg-data-profiling-4.19.1 filetype-1.2.0 imagehash-4.3.2 minify-html-0.18.1 multimethod-1.12 phik-0.12.5 puremagic-2.2.0 visions-0.8.1

In [3]:
import pandas as pd
import os
from ydata_profiling import ProfileReport

# ============================================
# 1. LOAD DATASET
# ============================================

file_path = "/content/2020_al_data_kaggle_upload_new_old_syllabi.csv"

if os.path.exists(file_path):

    df = pd.read_csv(file_path)

    print(f"Dataset loaded successfully from:")
    print(file_path)

    # ============================================
    # 2. BASIC DATASET INFORMATION
    # ============================================

    print("=" * 60)
    print("DATASET PROFILING")
    print("=" * 60)

    print("\nDataset Shape:")
    print("Rows    :", df.shape[0])
    print("Columns :", df.shape[1])

    print("\nColumn Names:")
    print(df.columns.tolist())

    print("\nData Types:")
    print(df.dtypes)

    # ============================================
    # 3. MISSING VALUES
    # ============================================

    print("\n" + "=" * 60)
    print("MISSING VALUES")
    print("=" * 60)

    missing = df.isnull().sum()

    missing_percentage = (missing / len(df)) * 100

    missing_report = pd.DataFrame({
        "Missing Values": missing,
        "Percentage": missing_percentage.round(2)
    })

    print(missing_report)

    # ============================================
    # 4. DUPLICATE RECORDS
    # ============================================

    print("\n" + "=" * 60)
    print("DUPLICATE RECORDS")
    print("=" * 60)

    duplicate_count = df.duplicated().sum()

    print("Number of duplicate records:", duplicate_count)

    # ============================================
    # 5. UNIQUE VALUES
    # ============================================

    print("\n" + "=" * 60)
    print("UNIQUE VALUES")
    print("=" * 60)

    print(df.nunique())

    # ============================================
    # 6. NUMERICAL STATISTICS
    # ============================================

    print("\n" + "=" * 60)
    print("NUMERICAL STATISTICS")
    print("=" * 60)

    print(df.describe())

    # ============================================
    # 7. CATEGORICAL VARIABLES
    # ============================================

    print("\n" + "=" * 60)
    print("CATEGORICAL VARIABLES")
    print("=" * 60)

    categorical_columns = df.select_dtypes(
        include=["object", "category"]
    ).columns

    for column in categorical_columns:

        print("\nColumn:", column)

        print(df[column].value_counts(dropna=False))

    # ============================================
    # 8. AUTOMATIC PROFILING REPORT
    # ============================================

    print("\nGenerating profiling report...")

    profile = ProfileReport(
        df,
        title="2020 A/L Dataset Profiling Report",
        explorative=True
    )

    profile.to_file("/content/dataset_profile.html")

    # ============================================
    # 9. COMPLETION MESSAGE
    # ============================================

    print("\n" + "=" * 60)
    print("PROFILING COMPLETED SUCCESSFULLY!")
    print("=" * 60)

    print("Report saved as:")
    print("/content/dataset_profile.html")

else:

    print("ERROR: Dataset not found!")

    print("\nPlease upload:")
    print("2020_al_data_kaggle_upload_new_old_syllabi.csv")

    print("\nIn Google Colab:")
    print("1. Click the folder icon on the left.")
    print("2. Click the Upload button.")
    print("3. Select your CSV file.")
    print("4. Run this cell again.")

/tmp/ipykernel_626/1413765591.py:3: DeprecationWarning:
    `import ydata_profiling` is deprecated and will not receive more updates.
    Please use `import data_profiling` instead.

  from ydata_profiling import ProfileReport

Dataset loaded successfully from:
/content/2020_al_data_kaggle_upload_new_old_syllabi.csv
============================================================
DATASET PROFILING
============================================================

Dataset Shape:
Rows    : 337553
Columns : 19

Column Names:
['index', 'stream', 'Zscore', 'district_rank', 'island_rank', 'al_year', 'sub1', 'sub1_r', 'sub2', 'sub2_r', 'sub3', 'sub3_r', 'cgt_r', 'ge_r', 'syllabus', 'birth_day', 'birth_month', 'birth_year', 'gender']

Data Types:
index             int64
stream           object
Zscore           object
district_rank    object
island_rank      object
al_year           int64
sub1             object
sub1_r           object
sub2             object
sub2_r           object
sub3             object
sub3_r           object
cgt_r            object
ge_r             object
syllabus         object
birth_day        object
birth_month      object
birth_year       object
gender           object
dtype: object

============================================================
MISSING VALUES
============================================================
               Missing Values  Percentage
index                       0        0.00
stream                      0        0.00
Zscore                      0        0.00
district_rank               0        0.00
island_rank                 0        0.00
al_year                     0        0.00
sub1                        0        0.00
sub1_r                      0        0.00
sub2                        0        0.00
sub2_r                      0        0.00
sub3                        0        0.00
sub3_r                      0        0.00
cgt_r                       0        0.00
ge_r                        0        0.00
syllabus                    0        0.00
birth_day                   0        0.00
birth_month                 0        0.00
birth_year                  0        0.00
gender                   1484        0.44

============================================================
DUPLICATE RECORDS
============================================================
Number of duplicate records: 0

============================================================
UNIQUE VALUES
============================================================
index            337553
stream                8
Zscore            33891
district_rank      8060
island_rank       47616
al_year               1
sub1                 51
sub1_r                7
sub2                 60
sub2_r                7
sub3                 60
sub3_r                8
cgt_r                73
ge_r                  7
syllabus              2
birth_day            34
birth_month          15
birth_year           76
gender                3
dtype: int64

============================================================
NUMERICAL STATISTICS
============================================================
               index   al_year
count  337553.000000  337553.0
mean   168776.000000    2020.0
std     97443.302045       0.0
min         0.000000    2020.0
25%     84388.000000    2020.0
50%    168776.000000    2020.0
75%    253164.000000    2020.0
max    337552.000000    2020.0

============================================================
CATEGORICAL VARIABLES
============================================================

Column: stream
stream
-                         150514
ARTS                       76547
COMMERCE                   39877
BIOLOGICAL SCIENCE         25768
PHYSICAL SCIENCE           21776
ENGINEERING TECHNOLOGY     12498
BIOSYSTEMS TECHNOLOGY       7833
NON                         2740
Name: count, dtype: int64

Column: Zscore
Zscore
-          105249
-.2435         30
.0958          27
-.1483         27
.0354          25
            ...
1.2269          1
-1.0013         1
-.9248          1
-1.4473         1
-1.2051         1
Name: count, Length: 33891, dtype: int64

Column: district_rank
district_rank
-            153254
11 (NEW)        152
9 (NEW)         151
6 (NEW)         150
1 (NEW)         150
              ...
545 (OLD)         1
512 (OLD)         1
569 (OLD)         1
452 (OLD)         1
539 (OLD)         1
Name: count, Length: 8060, dtype: int64

Column: island_rank
island_rank
-              153254
15404 (NEW)        21
10175 (NEW)        19
10890 (NEW)        19
20768 (NEW)        17
                ...
2049 (OLD)          1
5847 (OLD)          1
4329 (OLD)          1
5170 (OLD)          1
3573 (OLD)          1
Name: count, Length: 47616, dtype: int64

Column: sub1
sub1
PHYSICS                                   88758
ECONOMICS                                 66538
GEOGRAPHY                                 52478
POLITICAL SCIENCE                         36859
INFORMATION & COMMUNICATION TECHNOLOGY    35337
AGRICULTURAL SCIENCE                      18676
COMMUNICATION & MEDIA STUDIES             10410
HISTORY OF SRI LANKA & INDIA               6779
CHEMISTRY                                  5938
HOME ECONOMICS                             4187
LOGIC & SCIENTIFIC METHOD                  2877
HISTORY OF SRI LANKA & EUROPE              2474
BUDDHISM                                   1029
MATHEMATICS                                 673
HISTORY OF INDIA                            597
BUDDHIST CIVILIZATION                       577
AGRO TECHNOLOGY                             559
BUSINESS STUDIES                            391
ART                                         348
ISLAM                                       287
HINDU CIVILIZATION                          274
HISTORY OF EUROPE                           265
CIVIL TECHNOLOGY                            211
FOOD TECHNOLOGY                             151
GREEK & ROMAN CIVILIZATION                  125
CHRISTIANITY                                118
ISLAMIC CIVILIZATION                         85
HISTORY OF SRI LANKA & MODERN WORLD          75
ELECTRICAL,ELECTRONIC AND IT                 56
DANCING(INDIGENOUS)                          49
SINHALA                                      44
BUSINESS STATISTICS                          43
COMBINED MATHEMATICS                         40
MECHANICAL TECHNOLOGY                        40
CHRISTIAN CIVILIZATION                       31
ACCOUNTING                                   28
HINDUISM                                     23
ORIENTAL MUSIC                               20
HISTORY OF MODERN WORLD                      19
BIOLOGY                                      18
BIO-RESOURCE TECHNOLOGY                      17
DRAMA AND THEATRE (SINHALA)                  12
WESTERN MUSIC                                 8
ENGINEERING TECHNOLOGY                        7
BIO SYSTEMS TECHNOLOGY                        7
ENGLISH                                       4
TAMIL                                         3
DANCING(BHARATHA)                             3
CARNATIC MUSIC                                2
HIGHER MATHEMATICS                            2
PALI                                          1
Name: count, dtype: int64

Column: sub1_r
sub1_r
S           97338
F           79006
C           71764
Absent      43581
B           27111
A           18737
Withheld       16
Name: count, dtype: int64

Column: sub2
sub2
CHEMISTRY                                 83993
BUSINESS STUDIES                          62466
BUDDHIST CIVILIZATION                     27395
ENGINEERING TECHNOLOGY                    24388
POLITICAL SCIENCE                         18830
COMMUNICATION & MEDIA STUDIES             18792
BIO SYSTEMS TECHNOLOGY                    13482
GEOGRAPHY                                  8141
HISTORY OF SRI LANKA & INDIA               7853
LOGIC & SCIENTIFIC METHOD                  6593
AGRICULTURAL SCIENCE                       5898
DANCING(INDIGENOUS)                        5892
ISLAM                                      5665
HINDU CIVILIZATION                         5161
COMBINED MATHEMATICS                       4712
HOME ECONOMICS                             4538
ART                                        3857
HISTORY OF SRI LANKA & EUROPE              3841
ECONOMICS                                  3457
ISLAMIC CIVILIZATION                       2824
ORIENTAL MUSIC                             2333
CHRISTIANITY                               2142
DRAMA AND THEATRE (SINHALA)                1868
DRAMA AND THEATRE (TAMIL)                  1461
SINHALA                                    1425
CARNATIC MUSIC                             1340
CHRISTIAN CIVILIZATION                     1280
ENGLISH                                    1071
BUSINESS STATISTICS                         935
DANCING(BHARATHA)                           829
BUDDHISM                                    736
PALI                                        672
HINDUISM                                    632
HISTORY OF INDIA                            537
AGRO TECHNOLOGY                             502
INFORMATION & COMMUNICATION TECHNOLOGY      407
HISTORY OF EUROPE                           316
BIOLOGY                                     277
TAMIL                                       190
GREEK & ROMAN CIVILIZATION                  154
FRENCH                                      106
GERMAN                                       89
HISTORY OF SRI LANKA & MODERN WORLD          87
ACCOUNTING                                   74
WESTERN MUSIC                                50
CHINESE                                      49
HINDI                                        47
FOOD TECHNOLOGY                              45
MATHEMATICS                                  25
SCIENCE FOR TECHNOLOGY                       21
CIVIL TECHNOLOGY                             18
HISTORY OF MODERN WORLD                      15
BIO-RESOURCE TECHNOLOGY                       9
ELECTRICAL,ELECTRONIC AND IT                  9
RUSSIAN                                       7
DRAMA AND THEATRE (ENGLISH)                   5
SANSKRIT                                      4
MECHANICAL TECHNOLOGY                         3
ARABIC                                        3
HIGHER MATHEMATICS                            2
Name: count, dtype: int64

Column: sub2_r
sub2_r
S           89408
C           80261
F           59559
Absent      45556
B           37328
A           25425
Withheld       16
Name: count, dtype: int64

Column: sub3
sub3
SINHALA                                   75708
ACCOUNTING                                64900
BIOLOGY                                   50723
COMBINED MATHEMATICS                      39094
SCIENCE FOR TECHNOLOGY                    37869
TAMIL                                     22102
COMMUNICATION & MEDIA STUDIES              4931
INFORMATION & COMMUNICATION TECHNOLOGY     4840
ISLAM                                      4060
BUDDHIST CIVILIZATION                      4016
ARABIC                                     3234
ART                                        3180
DRAMA AND THEATRE (SINHALA)                2074
JAPANESE                                   1987
ISLAMIC CIVILIZATION                       1635
LOGIC & SCIENTIFIC METHOD                  1383
DANCING(INDIGENOUS)                        1344
DRAMA AND THEATRE (TAMIL)                  1203
HISTORY OF SRI LANKA & INDIA               1173
FRENCH                                     1172
HINDU CIVILIZATION                         1075
ENGLISH                                     956
ORIENTAL MUSIC                              879
POLITICAL SCIENCE                           836
PALI                                        743
SANSKRIT                                    699
CHRISTIANITY                                633
GEOGRAPHY                                   624
BUSINESS STUDIES                            550
HISTORY OF SRI LANKA & EUROPE               523
HOME ECONOMICS                              491
HINDI                                       479
CHINESE                                     353
GERMAN                                      342
CHRISTIAN CIVILIZATION                      284
CARNATIC MUSIC                              235
BUSINESS STATISTICS                         199
HINDUISM                                    160
DANCING(BHARATHA)                           156
AGRO TECHNOLOGY                             139
BIO SYSTEMS TECHNOLOGY                       79
BUDDHISM                                     76
GREEK & ROMAN CIVILIZATION                   51
MATHEMATICS                                  50
HISTORY OF INDIA                             50
HISTORY OF EUROPE                            44
WESTERN MUSIC                                40
ENGINEERING TECHNOLOGY                       39
RUSSIAN                                      31
HISTORY OF SRI LANKA & MODERN WORLD          30
ECONOMICS                                    28
CIVIL TECHNOLOGY                             12
HIGHER MATHEMATICS                           11
PHYSICS                                       9
FOOD TECHNOLOGY                               6
AGRICULTURAL SCIENCE                          5
CHEMISTRY                                     2
MECHANICAL TECHNOLOGY                         2
BIO-RESOURCE TECHNOLOGY                       2
HISTORY OF MODERN WORLD                       2
Name: count, dtype: int64

Column: sub3_r
sub3_r
S           88383
C           75781
F           55258
B           46710
Absent      43332
A           28023
Withheld       65
A.1             1
Name: count, dtype: int64

Column: cgt_r
cgt_r
Absent    76628
040       16182
042       15931
038       15462
044       15135
          ...
004           2
000           2
100           1
098           1
092           1
Name: count, Length: 73, dtype: int64

Column: ge_r
ge_r
F           123804
S            69820
Absent       66140
C            36080
A            23093
B            18600
Withheld        16
Name: count, dtype: int64

Column: syllabus
syllabus
new    306211
old     31342
Name: count, dtype: int64

Column: birth_day
birth_day
1                    11297
10                   11296
21                   11265
20                   11199
23                   11188
17                   11173
9                    11087
6                    11084
22                   11078
19                   11068
8                    11057
2                    11055
12                   11052
15                   11042
25                   11035
18                   11032
24                   11031
16                   11031
11                   10998
3                    10998
5                    10993
14                   10945
28                   10927
26                   10924
4                    10906
27                   10866
13                   10808
7                    10676
29                   10268
30                   10089
31                    6502
Invalid nic error     1484
Invalid day error       75
Major error             24
Name: count, dtype: int64

Column: birth_month
birth_month
May                  29424
October              29350
March                29203
April                28714
January              28616
July                 28182
November             28043
June                 27951
August               27584
September            27411
December             27225
February             24267
Invalid nic error     1484
Invalid day error       75
Major error             24
Name: count, dtype: int64

Column: birth_year
birth_year
2001    185402
2000     90735
1999     24155
2002     16236
1998      6561
         ...
1955         1
5957         1
9980         1
1952         1
6575         1
Name: count, Length: 76, dtype: int64

Column: gender
gender
female         193326
male           142719
NaN              1484
Major error        24
Name: count, dtype: int64

Generating profiling report...

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

  0%|          | 0/19 [00:00<?, ?it/s]
  5%|▌         | 1/19 [00:01<00:24,  1.36s/it]
 11%|█         | 2/19 [00:01<00:10,  1.58it/s]
 16%|█▌        | 3/19 [00:03<00:19,  1.20s/it]
 21%|██        | 4/19 [00:03<00:11,  1.30it/s]
 26%|██▋       | 5/19 [00:05<00:19,  1.37s/it]
 47%|████▋     | 9/19 [00:07<00:06,  1.54it/s]
 53%|█████▎    | 10/19 [00:07<00:05,  1.75it/s]
 58%|█████▊    | 11/19 [00:08<00:05,  1.58it/s]
 63%|██████▎   | 12/19 [00:08<00:03,  1.94it/s]
 68%|██████▊   | 13/19 [00:09<00:03,  1.59it/s]
 74%|███████▎  | 14/19 [00:09<00:02,  1.86it/s]
 79%|███████▉  | 15/19 [00:10<00:02,  1.90it/s]
 84%|████████▍ | 16/19 [00:10<00:01,  1.97it/s]
 89%|████████▉ | 17/19 [00:11<00:01,  1.95it/s]
 95%|█████████▍| 18/19 [00:11<00:00,  1.90it/s]
100%|██████████| 19/19 [00:12<00:00,  1.57it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]

============================================================
PROFILING COMPLETED SUCCESSFULLY!
============================================================
Report saved as:
/content/dataset_profile.html

In [5]:
import numpy as np

# 1. Remove non-numeric characters from 'island_rank' column
df['island_rank'] = df['island_rank'].astype(str).str.replace(r'[^0-9]', '', regex=True)

# 2. Convert the cleaned 'island_rank' column to numeric, coercing errors to NaN
df['island_rank'] = pd.to_numeric(df['island_rank'], errors='coerce')

# 3. Handle NaN values by filling with -1 as a placeholder
df['island_rank'] = df['island_rank'].fillna(-1).astype(int)

# 4. Display the data types and the first few rows of the 'island_rank' column to verify the changes
print("Data type of 'island_rank' after cleaning and conversion:")
print(df['island_rank'].dtype)
print("\nFirst 5 rows of 'island_rank' after cleaning and conversion:")
print(df['island_rank'].head())

Data type of 'island_rank' after cleaning and conversion:
int64

First 5 rows of 'island_rank' after cleaning and conversion:
0    64994
1    62338
2    37307
3    30449
4    17010
Name: island_rank, dtype: int64

In [6]:
df_a_grades = df[(df['sub1_r'] == 'A') & (df['sub2_r'] == 'A') & (df['sub3_r'] == 'A')]

print("Shape of DataFrame after filtering for 'A' grades:")
print(df_a_grades.shape)

print("\nFirst 5 rows of students with 'A' grades in all three subjects:")
display(df_a_grades.head())

Shape of DataFrame after filtering for 'A' grades:
(7692, 19)

First 5 rows of students with 'A' grades in all three subjects:

,df_index,stream,Zscore,district_rank,island_rank,al_year,sub1,sub1_r,sub2,sub2_r,sub3,sub3_r,cgt_r,ge_r,syllabus,birth_day,birth_month,birth_year,gender
49,49,ARTS,1.9997,108 (NEW),588,2020,ECONOMICS,A,POLITICAL SCIENCE,A,ISLAM,A,062,A,new,3,February,2001,female
54,54,ARTS,1.4195,585 (NEW),6563,2020,ECONOMICS,A,POLITICAL SCIENCE,A,ISLAM,A,038,B,new,20,July,2001,female
139,139,COMMERCE,1.8182,373 (NEW),1246,2020,ECONOMICS,A,BUSINESS STUDIES,A,ACCOUNTING,A,046,B,new,24,July,2001,male
166,166,COMMERCE,1.6087,717 (NEW),2713,2020,ECONOMICS,A,BUSINESS STUDIES,A,ACCOUNTING,A,064,B,new,26,July,2001,male
185,185,COMMERCE,1.7950,412 (NEW),1370,2020,ECONOMICS,A,BUSINESS STUDIES,A,ACCOUNTING,A,050,C,new,17,December,2001,male

In [7]:
df_filtered_rank = df_a_grades[df_a_grades['island_rank'] > 2500]

print("Shape of DataFrame after filtering by island_rank (> 2500):")
print(df_filtered_rank.shape)

print("\nFirst 5 rows of students with 'A' grades and island_rank > 2500:")
display(df_filtered_rank.head())

Shape of DataFrame after filtering by island_rank (> 2500):
(1822, 19)

First 5 rows of students with 'A' grades and island_rank > 2500:

,df_index,stream,Zscore,district_rank,island_rank,al_year,sub1,sub1_r,sub2,sub2_r,sub3,sub3_r,cgt_r,ge_r,syllabus,birth_day,birth_month,birth_year,gender
54,54,ARTS,1.4195,585 (NEW),6563,2020,ECONOMICS,A,POLITICAL SCIENCE,A,ISLAM,A,038,B,new,20,July,2001,female
166,166,COMMERCE,1.6087,717 (NEW),2713,2020,ECONOMICS,A,BUSINESS STUDIES,A,ACCOUNTING,A,064,B,new,26,July,2001,male
491,491,COMMERCE,1.5054,922 (NEW),3688,2020,ECONOMICS,A,BUSINESS STUDIES,A,ACCOUNTING,A,032,A,new,24,January,2002,female
589,589,COMMERCE,1.3893,1180 (NEW),5023,2020,ECONOMICS,A,BUSINESS STUDIES,A,ACCOUNTING,A,054,A,new,3,April,2001,female
597,597,COMMERCE,1.6203,695 (NEW),2637,2020,ECONOMICS,A,BUSINESS STUDIES,A,ACCOUNTING,A,054,A,new,8,July,2001,female

In [9]:
print(f"Total number of students satisfying both conditions: {len(df_filtered_rank)}")

print("\nFirst 10 rows of the filtered DataFrame:")
display(df_filtered_rank.head(10))

print("\nDescriptive statistics for Zscore:")
# Convert Zscore to numeric, handling errors by coercing to NaN, then fill NaN values with 0 before calculating statistics.
# Ensure df_filtered_rank is a proper copy to avoid SettingWithCopyWarning
df_filtered_rank_copy = df_filtered_rank.copy()
df_filtered_rank_copy['Zscore'] = pd.to_numeric(df_filtered_rank_copy['Zscore'], errors='coerce').fillna(0)
print(df_filtered_rank_copy['Zscore'].describe())

print("\nDescriptive statistics for island_rank:")
print(df_filtered_rank_copy['island_rank'].describe())

print("\nValue counts for sub1_r (Grade for Subject 1):")
print(df_filtered_rank_copy['sub1_r'].value_counts())

print("\nValue counts for sub2_r (Grade for Subject 2):")
print(df_filtered_rank_copy['sub2_r'].value_counts())

print("\nValue counts for sub3_r (Grade for Subject 3):")
print(df_filtered_rank_copy['sub3_r'].value_counts())

Total number of students satisfying both conditions: 1822

First 10 rows of the filtered DataFrame:

,df_index,stream,Zscore,district_rank,island_rank,al_year,sub1,sub1_r,sub2,sub2_r,sub3,sub3_r,cgt_r,ge_r,syllabus,birth_day,birth_month,birth_year,gender
54,54,ARTS,1.4195,585 (NEW),6563,2020,ECONOMICS,A,POLITICAL SCIENCE,A,ISLAM,A,038,B,new,20,July,2001,female
166,166,COMMERCE,1.6087,717 (NEW),2713,2020,ECONOMICS,A,BUSINESS STUDIES,A,ACCOUNTING,A,064,B,new,26,July,2001,male
491,491,COMMERCE,1.5054,922 (NEW),3688,2020,ECONOMICS,A,BUSINESS STUDIES,A,ACCOUNTING,A,032,A,new,24,January,2002,female
589,589,COMMERCE,1.3893,1180 (NEW),5023,2020,ECONOMICS,A,BUSINESS STUDIES,A,ACCOUNTING,A,054,A,new,3,April,2001,female
597,597,COMMERCE,1.6203,695 (NEW),2637,2020,ECONOMICS,A,BUSINESS STUDIES,A,ACCOUNTING,A,054,A,new,8,July,2001,female
659,659,COMMERCE,1.6017,731 (NEW),2768,2020,ECONOMICS,A,BUSINESS STUDIES,A,ACCOUNTING,A,064,A,new,31,May,2001,female
719,719,COMMERCE,1.6141,705 (NEW),2679,2020,ECONOMICS,A,BUSINESS STATISTICS,A,ACCOUNTING,A,062,A,new,15,November,2001,female
1249,1249,ARTS,1.5991,398 (NEW),3673,2020,GEOGRAPHY,A,POLITICAL SCIENCE,A,ISLAMIC CIVILIZATION,A,036,B,new,23,March,2001,female
1287,1287,ARTS,1.4919,504 (NEW),5252,2020,GEOGRAPHY,A,POLITICAL SCIENCE,A,ISLAMIC CIVILIZATION,A,042,A,new,30,July,2001,female
1323,1323,COMMERCE,1.4422,1062 (NEW),4389,2020,ECONOMICS,A,BUSINESS STUDIES,A,ACCOUNTING,A,054,B,new,6,April,2001,female

Descriptive statistics for Zscore:
count    1822.000000
mean        1.546640
std         0.089601
min         1.117400
25%         1.490225
50%         1.559350
75%         1.613900
max         1.696700
Name: Zscore, dtype: float64

Descriptive statistics for island_rank:
count     1822.000000
mean      3833.002744
std       1295.618969
min       2502.000000
25%       2927.750000
50%       3491.000000
75%       4303.750000
max      13726.000000
Name: island_rank, dtype: float64

Value counts for sub1_r (Grade for Subject 1):
sub1_r
A    1822
Name: count, dtype: int64

Value counts for sub2_r (Grade for Subject 2):
sub2_r
A    1822
Name: count, dtype: int64

Value counts for sub3_r (Grade for Subject 3):
sub3_r
A    1822
Name: count, dtype: int64

In [10]:
df_filtered_rank.to_csv('filtered_students_data.csv', index=False)
print("Filtered data saved to 'filtered_students_data.csv'")

Filtered data saved to 'filtered_students_data.csv'

In [11]:
from google.colab import drive
drive.mount('/content/drive')

MessageError: Error: credential propagation was unsuccessful

In [12]:
import numpy as np

# 1. Remove non-numeric characters from 'island_rank' column
df['island_rank'] = df['island_rank'].astype(str).str.replace(r'[^0-9]', '', regex=True)

# 2. Convert the cleaned 'island_rank' column to numeric, coercing errors to NaN
df['island_rank'] = pd.to_numeric(df['island_rank'], errors='coerce')

# 3. Handle NaN values by filling with -1 as a placeholder
df['island_rank'] = df['island_rank'].fillna(-1).astype(int)

# 4. Display the data types and the first few rows of the 'island_rank' column to verify the changes
print("Data type of 'island_rank' after cleaning and conversion:")
print(df['island_rank'].dtype)
print("\nFirst 5 rows of 'island_rank' after cleaning and conversion:")
print(df['island_rank'].head())

Data type of 'island_rank' after cleaning and conversion:
int64

First 5 rows of 'island_rank' after cleaning and conversion:
0    64994
1    62338
2    37307
3    30449
4    17010
Name: island_rank, dtype: int64

In [13]:
df_a_grades = df[(df['sub1_r'] == 'A') & (df['sub2_r'] == 'A') & (df['sub3_r'] == 'A')]

print("Shape of DataFrame after filtering for 'A' grades:")
print(df_a_grades.shape)

print("\nFirst 5 rows of students with 'A' grades in all three subjects:")
print(df_a_grades.head())

Shape of DataFrame after filtering for 'A' grades:
(7692, 19)

First 5 rows of students with 'A' grades in all three subjects:
     df_index    stream  Zscore district_rank  island_rank  al_year  \
49         49      ARTS  1.9997     108 (NEW)          588     2020
54         54      ARTS  1.4195     585 (NEW)         6563     2020
139       139  COMMERCE  1.8182     373 (NEW)         1246     2020
166       166  COMMERCE  1.6087     717 (NEW)         2713     2020
185       185  COMMERCE  1.7950     412 (NEW)         1370     2020

          sub1 sub1_r               sub2 sub2_r        sub3 sub3_r cgt_r ge_r  \
49   ECONOMICS      A  POLITICAL SCIENCE      A       ISLAM      A   062    A
54   ECONOMICS      A  POLITICAL SCIENCE      A       ISLAM      A   038    B
139  ECONOMICS      A   BUSINESS STUDIES      A  ACCOUNTING      A   046    B
166  ECONOMICS      A   BUSINESS STUDIES      A  ACCOUNTING      A   064    B
185  ECONOMICS      A   BUSINESS STUDIES      A  ACCOUNTING      A   050    C

    syllabus birth_day birth_month birth_year  gender
49       new         3    February       2001  female
54       new        20        July       2001  female
139      new        24        July       2001    male
166      new        26        July       2001    male
185      new        17    December       2001    male

In [14]:
df_filtered_rank = df_a_grades[df_a_grades['island_rank'] > 2500]

print("Shape of DataFrame after filtering by island_rank (> 2500):")
print(df_filtered_rank.shape)

print("\nFirst 5 rows of students with 'A' grades and island_rank > 2500:")
print(df_filtered_rank.head())

Shape of DataFrame after filtering by island_rank (> 2500):
(1822, 19)

First 5 rows of students with 'A' grades and island_rank > 2500:
     df_index    stream  Zscore district_rank  island_rank  al_year  \
54         54      ARTS  1.4195     585 (NEW)         6563     2020
166       166  COMMERCE  1.6087     717 (NEW)         2713     2020
491       491  COMMERCE  1.5054     922 (NEW)         3688     2020
589       589  COMMERCE  1.3893    1180 (NEW)         5023     2020
597       597  COMMERCE  1.6203     695 (NEW)         2637     2020

          sub1 sub1_r               sub2 sub2_r        sub3 sub3_r cgt_r ge_r  \
54   ECONOMICS      A  POLITICAL SCIENCE      A       ISLAM      A   038    B
166  ECONOMICS      A   BUSINESS STUDIES      A  ACCOUNTING      A   064    B
491  ECONOMICS      A   BUSINESS STUDIES      A  ACCOUNTING      A   032    A
589  ECONOMICS      A   BUSINESS STUDIES      A  ACCOUNTING      A   054    A
597  ECONOMICS      A   BUSINESS STUDIES      A  ACCOUNTING      A   054    A

    syllabus birth_day birth_month birth_year  gender
54       new        20        July       2001  female
166      new        26        July       2001    male
491      new        24     January       2002  female
589      new         3       April       2001  female
597      new         8        July       2001  female

In [15]:
print(f"Total number of students satisfying both conditions: {len(df_filtered_rank)}")

print("\nFirst 10 rows of the filtered DataFrame:")
print(df_filtered_rank.head(10))

Total number of students satisfying both conditions: 1822

First 10 rows of the filtered DataFrame:
      df_index    stream  Zscore district_rank  island_rank  al_year  \
54          54      ARTS  1.4195     585 (NEW)         6563     2020
166        166  COMMERCE  1.6087     717 (NEW)         2713     2020
491        491  COMMERCE  1.5054     922 (NEW)         3688     2020
589        589  COMMERCE  1.3893    1180 (NEW)         5023     2020
597        597  COMMERCE  1.6203     695 (NEW)         2637     2020
659        659  COMMERCE  1.6017     731 (NEW)         2768     2020
719        719  COMMERCE  1.6141     705 (NEW)         2679     2020
1249      1249      ARTS  1.5991     398 (NEW)         3673     2020
1287      1287      ARTS  1.4919     504 (NEW)         5252     2020
1323      1323  COMMERCE  1.4422    1062 (NEW)         4389     2020

           sub1 sub1_r                 sub2 sub2_r                  sub3  \
54    ECONOMICS      A    POLITICAL SCIENCE      A                 ISLAM
166   ECONOMICS      A     BUSINESS STUDIES      A            ACCOUNTING
491   ECONOMICS      A     BUSINESS STUDIES      A            ACCOUNTING
589   ECONOMICS      A     BUSINESS STUDIES      A            ACCOUNTING
597   ECONOMICS      A     BUSINESS STUDIES      A            ACCOUNTING
659   ECONOMICS      A     BUSINESS STUDIES      A            ACCOUNTING
719   ECONOMICS      A  BUSINESS STATISTICS      A            ACCOUNTING
1249  GEOGRAPHY      A    POLITICAL SCIENCE      A  ISLAMIC CIVILIZATION
1287  GEOGRAPHY      A    POLITICAL SCIENCE      A  ISLAMIC CIVILIZATION
1323  ECONOMICS      A     BUSINESS STUDIES      A            ACCOUNTING

     sub3_r cgt_r ge_r syllabus birth_day birth_month birth_year  gender
54        A   038    B      new        20        July       2001  female
166       A   064    B      new        26        July       2001    male
491       A   032    A      new        24     January       2002  female
589       A   054    A      new         3       April       2001  female
597       A   054    A      new         8        July       2001  female
659       A   064    A      new        31         May       2001  female
719       A   062    A      new        15    November       2001  female
1249      A   036    B      new        23       March       2001  female
1287      A   042    A      new        30        July       2001  female
1323      A   054    B      new         6       April       2001  female

In [16]:
print("\nDescriptive statistics for Zscore:")
# Convert Zscore to numeric, handling errors by coercing to NaN, then fill NaN values with 0 before calculating statistics.
df_filtered_rank['Zscore'] = pd.to_numeric(df_filtered_rank['Zscore'], errors='coerce').fillna(0)
print(df_filtered_rank['Zscore'].describe())

print("\nDescriptive statistics for island_rank:")
print(df_filtered_rank['island_rank'].describe())

print("\nValue counts for sub1_r (Grade for Subject 1):")
print(df_filtered_rank['sub1_r'].value_counts())

print("\nValue counts for sub2_r (Grade for Subject 2):")
print(df_filtered_rank['sub2_r'].value_counts())

print("\nValue counts for sub3_r (Grade for Subject 3):")
print(df_filtered_rank['sub3_r'].value_counts())

Descriptive statistics for Zscore:
count    1822.000000
mean        1.546640
std         0.089601
min         1.117400
25%         1.490225
50%         1.559350
75%         1.613900
max         1.696700
Name: Zscore, dtype: float64

Descriptive statistics for island_rank:
count     1822.000000
mean      3833.002744
std       1295.618969
min       2502.000000
25%       2927.750000
50%       3491.000000
75%       4303.750000
max      13726.000000
Name: island_rank, dtype: float64

Value counts for sub1_r (Grade for Subject 1):
sub1_r
A    1822
Name: count, dtype: int64

Value counts for sub2_r (Grade for Subject 2):
sub2_r
A    1822
Name: count, dtype: int64

Value counts for sub3_r (Grade for Subject 3):
sub3_r
A    1822
Name: count, dtype: int64

/tmp/ipykernel_626/1285777067.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_filtered_rank['Zscore'] = pd.to_numeric(df_filtered_rank['Zscore'], errors='coerce').fillna(0)

In [17]:
print("\nDescriptive statistics for Zscore:")
# Create a copy of df_filtered_rank to avoid SettingWithCopyWarning
df_filtered_rank = df_filtered_rank.copy()
# Convert Zscore to numeric, handling errors by coercing to NaN, then fill NaN values with 0 before calculating statistics.
df_filtered_rank['Zscore'] = pd.to_numeric(df_filtered_rank['Zscore'], errors='coerce').fillna(0)
print(df_filtered_rank['Zscore'].describe())

print("\nDescriptive statistics for island_rank:")
print(df_filtered_rank['island_rank'].describe())

print("\nValue counts for sub1_r (Grade for Subject 1):")
print(df_filtered_rank['sub1_r'].value_counts())

print("\nValue counts for sub2_r (Grade for Subject 2):")
print(df_filtered_rank['sub2_r'].value_counts())

print("\nValue counts for sub3_r (Grade for Subject 3):")
print(df_filtered_rank['sub3_r'].value_counts())

Descriptive statistics for Zscore:
count    1822.000000
mean        1.546640
std         0.089601
min         1.117400
25%         1.490225
50%         1.559350
75%         1.613900
max         1.696700
Name: Zscore, dtype: float64

Descriptive statistics for island_rank:
count     1822.000000
mean      3833.002744
std       1295.618969
min       2502.000000
25%       2927.750000
50%       3491.000000
75%       4303.750000
max      13726.000000
Name: island_rank, dtype: float64

Value counts for sub1_r (Grade for Subject 1):
sub1_r
A    1822
Name: count, dtype: int64

Value counts for sub2_r (Grade for Subject 2):
sub2_r
A    1822
Name: count, dtype: int64

Value counts for sub3_r (Grade for Subject 3):
sub3_r
A    1822
Name: count, dtype: int64

In [18]:
df_filtered_rank.to_csv('filtered_students_data.csv', index=False)
print("Filtered data saved to 'filtered_students_data.csv'")

Filtered data saved to 'filtered_students_data.csv'

In [20]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder

# ============================================================
# 1. LOAD DATASET
# ============================================================

file_path = "/content/filtered_students_data.csv"

df = pd.read_csv(file_path)

print("=" * 60)
print("ORIGINAL DATASET")
print("=" * 60)

print("Rows:", df.shape[0])
print("Columns:", df.shape[1])
print("\nColumns:")
print(df.columns.tolist())


# ============================================================
# 2. REMOVE UNNECESSARY INDEX COLUMN
# ============================================================

if "df_index" in df.columns:
    df = df.drop(columns=["df_index"])

print("\nRemoved df_index column.")


# ============================================================
# 3. REMOVE DUPLICATE RECORDS
# ============================================================

before = len(df)

df = df.drop_duplicates()

after = len(df)

print(f"Duplicates removed: {before - after}")


# ============================================================
# 4. CLEAN STRING COLUMNS
# ============================================================

string_columns = df.select_dtypes(include="object").columns

for col in string_columns:
    df[col] = df[col].astype(str).str.strip()

    # Convert common missing-value representations to NaN
    df[col] = df[col].replace(
        ["", "NA", "N/A", "na", "n/a", "NULL", "null", "-", "--"],
        np.nan
    )


# ============================================================
# 5. CONVERT NUMERIC COLUMNS
# ============================================================

numeric_columns = [
    "Zscore",
    "district_rank",
    "island_rank",
    "al_year",
    "sub1_r",
    "sub2_r",
    "sub3_r",
    "cgt_r",
    "ge_r",
    "birth_day",
    "birth_year"
]

for col in numeric_columns:
    if col in df.columns:
        df[col] = pd.to_numeric(df[col], errors="coerce")


# ============================================================
# 6. CONVERT BIRTH MONTH TO NUMBER
# ============================================================

month_mapping = {
    "January": 1,
    "February": 2,
    "March": 3,
    "April": 4,
    "May": 5,
    "June": 6,
    "July": 7,
    "August": 8,
    "September": 9,
    "October": 10,
    "November": 11,
    "December": 12
}

if "birth_month" in df.columns:
    df["birth_month_num"] = (
        df["birth_month"]
        .map(month_mapping)
    )


# ============================================================
# 7. CONVERT SUBJECT GRADES TO NUMERIC VALUES
# ============================================================

# A/L grade hierarchy
grade_mapping = {
    "A": 5,
    "B": 4,
    "C": 3,
    "S": 2,
    "W": 0,
    "F": 0
}

grade_columns = ["sub1", "sub2", "sub3"]

for col in grade_columns:
    if col in df.columns:
        df[col + "_encoded"] = (
            df[col]
            .str.upper()
            .map(grade_mapping)
        )


# ============================================================
# 8. ENCODE GENDER
# ============================================================

gender_mapping = {
    "male": 0,
    "female": 1
}

if "gender" in df.columns:
    df["gender_encoded"] = (
        df["gender"]
        .str.lower()
        .map(gender_mapping)
    )


# ============================================================
# 9. ENCODE STREAM
# ============================================================

if "stream" in df.columns:

    stream_encoder = LabelEncoder()

    df["stream_encoded"] = stream_encoder.fit_transform(
        df["stream"].astype(str)
    )

    print("\nStream Encoding:")
    for value, encoded in zip(
        stream_encoder.classes_,
        range(len(stream_encoder.classes_))
    ):
        print(value, "=", encoded)


# ============================================================
# 10. ENCODE SYLLABUS
# ============================================================

if "syllabus" in df.columns:

    syllabus_encoder = LabelEncoder()

    df["syllabus_encoded"] = syllabus_encoder.fit_transform(
        df["syllabus"].astype(str)
    )

    print("\nSyllabus Encoding:")
    for value, encoded in zip(
        syllabus_encoder.classes_,
        range(len(syllabus_encoder.classes_))
    ):
        print(value, "=", encoded)


# ============================================================
# 11. CREATE AGE AT A/L YEAR
# ============================================================

if "al_year" in df.columns and "birth_year" in df.columns:

    df["age_at_al"] = (
        df["al_year"] - df["birth_year"]
    )

    # Remove impossible ages
    df.loc[
        (df["age_at_al"] < 15) |
        (df["age_at_al"] > 30),
        "age_at_al"
    ] = np.nan


# ============================================================
# 12. HANDLE MISSING NUMERIC VALUES
# ============================================================

numeric_cols = df.select_dtypes(
    include=["int64", "float64"]
).columns

for col in numeric_cols:

    if df[col].isnull().sum() > 0:
        df[col] = df[col].fillna(
            df[col].median()
        )


# ============================================================
# 13. HANDLE MISSING CATEGORICAL VALUES
# ============================================================

categorical_cols = df.select_dtypes(
    include=["object"]
).columns

for col in categorical_cols:

    if df[col].isnull().sum() > 0:
        df[col] = df[col].fillna("Unknown")


# ============================================================
# 14. CHECK TRANSFORMED DATA
# ============================================================

print("\n" + "=" * 60)
print("TRANSFORMED DATASET")
print("=" * 60)

print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

print("\nData Types:")
print(df.dtypes)

print("\nMissing Values:")
print(df.isnull().sum())


# ============================================================
# 15. SAVE TRANSFORMED DATASET
# ============================================================

output_file = "/content/transformed_students_data.csv"

df.to_csv(
    output_file,
    index=False
)

print("\n" + "=" * 60)
print("TRANSFORMATION COMPLETED")
print("=" * 60)

print("Saved to:")
print(output_file)


# ============================================================
# 16. DISPLAY FIRST 10 RECORDS
# ============================================================

print("\nFirst 10 transformed records:")

display(df.head(10))

============================================================
ORIGINAL DATASET
============================================================
Rows: 1822
Columns: 19

Columns:
['df_index', 'stream', 'Zscore', 'district_rank', 'island_rank', 'al_year', 'sub1', 'sub1_r', 'sub2', 'sub2_r', 'sub3', 'sub3_r', 'cgt_r', 'ge_r', 'syllabus', 'birth_day', 'birth_month', 'birth_year', 'gender']

Removed df_index column.
Duplicates removed: 0

Stream Encoding:
ARTS = 0
COMMERCE = 1

Syllabus Encoding:
new = 0

============================================================
TRANSFORMED DATASET
============================================================
Rows: 1822
Columns: 26

Data Types:
stream               object
Zscore              float64
district_rank       float64
island_rank           int64
al_year               int64
sub1                 object
sub1_r              float64
sub2                 object
sub2_r              float64
sub3                 object
sub3_r              float64
cgt_r               float64
ge_r                float64
syllabus             object
birth_day           float64
birth_month          object
birth_year          float64
gender               object
birth_month_num     float64
sub1_encoded        float64
sub2_encoded        float64
sub3_encoded        float64
gender_encoded      float64
stream_encoded        int64
syllabus_encoded      int64
age_at_al           float64
dtype: object

Missing Values:
stream                 0
Zscore                 0
district_rank       1822
island_rank            0
al_year                0
sub1                   0
sub1_r              1822
sub2                   0
sub2_r              1822
sub3                   0
sub3_r              1822
cgt_r                  0
ge_r                1822
syllabus               0
birth_day              0
birth_month            0
birth_year             0
gender                 0
birth_month_num        0
sub1_encoded        1822
sub2_encoded        1822
sub3_encoded        1822
gender_encoded         0
stream_encoded         0
syllabus_encoded       0
age_at_al              0
dtype: int64

============================================================
TRANSFORMATION COMPLETED
============================================================
Saved to:
/content/transformed_students_data.csv

First 10 transformed records:

,stream,Zscore,district_rank,island_rank,al_year,sub1,sub1_r,sub2,sub2_r,sub3,...,birth_year,gender,birth_month_num,sub1_encoded,sub2_encoded,sub3_encoded,gender_encoded,stream_encoded,syllabus_encoded,age_at_al
0,ARTS,1.4195,NaN,6563,2020,ECONOMICS,NaN,POLITICAL SCIENCE,NaN,ISLAM,...,2001.0,female,7.0,NaN,NaN,NaN,1.0,0,0,19.0
1,COMMERCE,1.6087,NaN,2713,2020,ECONOMICS,NaN,BUSINESS STUDIES,NaN,ACCOUNTING,...,2001.0,male,7.0,NaN,NaN,NaN,0.0,1,0,19.0
2,COMMERCE,1.5054,NaN,3688,2020,ECONOMICS,NaN,BUSINESS STUDIES,NaN,ACCOUNTING,...,2002.0,female,1.0,NaN,NaN,NaN,1.0,1,0,18.0
3,COMMERCE,1.3893,NaN,5023,2020,ECONOMICS,NaN,BUSINESS STUDIES,NaN,ACCOUNTING,...,2001.0,female,4.0,NaN,NaN,NaN,1.0,1,0,19.0
4,COMMERCE,1.6203,NaN,2637,2020,ECONOMICS,NaN,BUSINESS STUDIES,NaN,ACCOUNTING,...,2001.0,female,7.0,NaN,NaN,NaN,1.0,1,0,19.0
5,COMMERCE,1.6017,NaN,2768,2020,ECONOMICS,NaN,BUSINESS STUDIES,NaN,ACCOUNTING,...,2001.0,female,5.0,NaN,NaN,NaN,1.0,1,0,19.0
6,COMMERCE,1.6141,NaN,2679,2020,ECONOMICS,NaN,BUSINESS STATISTICS,NaN,ACCOUNTING,...,2001.0,female,11.0,NaN,NaN,NaN,1.0,1,0,19.0
7,ARTS,1.5991,NaN,3673,2020,GEOGRAPHY,NaN,POLITICAL SCIENCE,NaN,ISLAMIC CIVILIZATION,...,2001.0,female,3.0,NaN,NaN,NaN,1.0,0,0,19.0
8,ARTS,1.4919,NaN,5252,2020,GEOGRAPHY,NaN,POLITICAL SCIENCE,NaN,ISLAMIC CIVILIZATION,...,2001.0,female,7.0,NaN,NaN,NaN,1.0,0,0,19.0
9,COMMERCE,1.4422,NaN,4389,2020,ECONOMICS,NaN,BUSINESS STUDIES,NaN,ACCOUNTING,...,2001.0,female,4.0,NaN,NaN,NaN,1.0,1,0,19.0